name: club_easy_hotel
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+5

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^12.0.0
  http: ^1.2.1
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.3
  url_launcher: ^6.2.6
  webview_flutter: ^4.7.0
  provider: ^6.1.2
  app_links: 6.1.4
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: 2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1


flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
